package goflags

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	permissionutil "github.com/projectdiscovery/utils/permission"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func TestMain(m *testing.M) {
	DisableAutoConfigMigration = true
	os.Exit(m.Run())
}

func TestGenerateDefaultConfig(t *testing.T) {
	flagSet := NewFlagSet()

	example := `# generated by https://github.com/projectdiscovery/goflags

# default value for a test flag example
#test: test-default-value

# string slice flag example value
#slice: ["item1", "item2"]`

	var data string
	var data2 StringSlice
	flagSet.StringVar(&data, "test", "test-default-value", "Default value for a test flag example")
	flagSet.StringSliceVar(&data2, "slice", []string{"item1", "item2"}, "String slice flag example value", StringSliceOptions)
	defaultConfig := string(flagSet.generateDefaultConfig(flagSet.Marshal))
	parts := strings.SplitN(defaultConfig, "\n", 2)

	require.Equal(t, example, parts[1], "could not get correct default config")
	tearDown(t.Name())
}

func TestGenerateDefaultConfigUsesCanonicalAlias(t *testing.T) {
	flagSet := NewFlagSet()
	var value string
	flagSet.StringVarP(&value, "aliased", "a", "compiled", "aliased value")

	var config map[string]interface{}
	require.NoError(t, yaml.Unmarshal(flagSet.generateDefaultConfig(true), &config))
	require.Equal(t, map[string]interface{}{"aliased": "compiled"}, config)
}

func TestGenerateDefaultConfigOmitsCallbackExamples(t *testing.T) {
	flagSet := NewFlagSet()
	flagSet.CallbackVar(func() {}, "update", "update tool")
	var value string
	flagSet.StringVar(&value, "value", "compiled", "test value")

	config := string(flagSet.generateDefaultConfig(false))
	require.NotContains(t, config, "#update:")
	require.Contains(t, config, "#value: compiled")
}

func TestConfigFileDataTypes(t *testing.T) {
	flagSet := NewFlagSet()
	var data string
	var data2 StringSlice
	var data3 int
	var data4 bool
	var data5 time.Duration
	var data6 int64

	flagSet.StringVar(&data, "string-value", "", "Default value for a test flag example")
	flagSet.StringSliceVar(&data2, "slice-value", []string{}, "String slice flag example value", StringSliceOptions)
	flagSet.IntVar(&data3, "int-value", 0, "Int value example")
	flagSet.BoolVar(&data4, "bool-value", false, "Bool value example")
	flagSet.DurationVar(&data5, "duration-value", time.Hour, "Bool value example")
	flagSet.Int64Var(&data6, "int64-value", 0, "Int64 value example")

	configFileData := `
string-value: test
slice-value:
 - test
 - test2
severity:
 - info
 - high
int-value: 543
bool-value: true
duration-value: 1h
int64-value: 9876543210`
	configFile := filepath.Join(t.TempDir(), "config.yaml")
	writeTestConfig(t, configFile, configFileData)

	err := flagSet.MergeConfigFile(configFile)
	require.Nil(t, err, "could not merge temporary config")

	require.Equal(t, "test", data, "could not get correct string")
	require.Equal(t, StringSlice{"test", "test2"}, data2, "could not get correct string slice")
	require.Equal(t, 543, data3, "could not get correct int")
	require.Equal(t, true, data4, "could not get correct bool")
	require.Equal(t, time.Hour, data5, "could not get correct duration")
	require.Equal(t, int64(9876543210), data6, "could not get correct int64")

	tearDown(t.Name())
}

func TestConfigFileCascade(t *testing.T) {
	tempDir := t.TempDir()
	systemConfig := filepath.Join(tempDir, "system.yaml")
	userConfig := filepath.Join(tempDir, "user.yaml")
	writeTestConfig(t, systemConfig, `
value: system
system-only: true
items:
  - system
values:
  - system=1
config-only:
  - system
aliased: system
`)
	writeTestConfig(t, userConfig, `
value: user
items:
  - user
values:
  - user=2
config-only:
  - user
a: user
`)

	flagSet := NewFlagSet()
	var (
		value      string
		systemOnly bool
		items      StringSlice
		values     RuntimeMap
		configOnly StringSlice
		aliased    string
	)
	flagSet.StringVar(&value, "value", "compiled", "test value")
	flagSet.BoolVar(&systemOnly, "system-only", false, "system value")
	flagSet.StringSliceVar(&items, "items", []string{"compiled"}, "test items", StringSliceOptions)
	flagSet.RuntimeMapVar(&values, "values", []string{"compiled=1"}, "test values")
	flagSet.StringSliceVarConfigOnly(&configOnly, "config-only", []string{"compiled"}, "config-only value")
	flagSet.StringVarP(&aliased, "aliased", "a", "compiled", "aliased value")
	flagSet.SetConfigFilePaths(systemConfig, userConfig)

	require.NoError(t, flagSet.Parse(""))
	require.Equal(t, "user", value)
	require.True(t, systemOnly)
	require.Equal(t, StringSlice{"user"}, items)
	require.Equal(t, map[string]interface{}{"user": "2"}, values.AsMap())
	require.Equal(t, StringSlice{"user"}, configOnly)
	require.Equal(t, "user", aliased)
}

func TestConfigFileCascadeExplicitDefaults(t *testing.T) {
	tempDir := t.TempDir()
	systemConfig := filepath.Join(tempDir, "system.yaml")
	userConfig := filepath.Join(tempDir, "user.yaml")
	writeTestConfig(t, systemConfig, "user-default: system\ncli-default: system\n")
	writeTestConfig(t, userConfig, "user-default: compiled\ncli-default: user\n")

	flagSet := NewFlagSet()
	var userDefault, cliDefault string
	flagSet.StringVar(&userDefault, "user-default", "compiled", "user default")
	flagSet.StringVarP(&cliDefault, "cli-default", "c", "compiled", "CLI default")
	flagSet.SetConfigFilePaths(systemConfig, userConfig)

	require.NoError(t, flagSet.Parse("-c", "compiled"))
	require.Equal(t, "compiled", userDefault)
	require.Equal(t, "compiled", cliDefault)
}

func TestConfigFileCascadeEmptyCollection(t *testing.T) {
	tempDir := t.TempDir()
	systemConfig := filepath.Join(tempDir, "system.yaml")
	userConfig := filepath.Join(tempDir, "user.yaml")
	writeTestConfig(t, systemConfig, "items:\n  - system\n")
	writeTestConfig(t, userConfig, "items: []\n")

	flagSet := NewFlagSet()
	var items StringSlice
	flagSet.StringSliceVar(&items, "items", []string{"compiled"}, "test items", StringSliceOptions)
	flagSet.SetConfigFilePaths(systemConfig, userConfig)

	require.NoError(t, flagSet.Parse(""))
	require.Empty(t, items)
}

func TestConfigFileCascadeCreatesPrimaryFile(t *testing.T) {
	tempDir := t.TempDir()
	systemConfig := filepath.Join(tempDir, "system.yaml")
	userConfig := filepath.Join(tempDir, "user", "config.yaml")
	writeTestConfig(t, systemConfig, "value: system\n")

	flagSet := NewFlagSet()
	var value string
	flagSet.StringVar(&value, "value", "compiled", "test value")
	flagSet.SetConfigFilePaths(systemConfig, userConfig)

	require.NoError(t, flagSet.Parse(""))
	require.Equal(t, "system", value)
	require.FileExists(t, userConfig)
}

func TestConfigFileCascadeGeneratedPrimaryDoesNotOverrideLowerPriority(t *testing.T) {
	tempDir := t.TempDir()
	systemConfig := filepath.Join(tempDir, "system.yaml")
	userConfig := filepath.Join(tempDir, "user", "config.yaml")
	writeTestConfig(t, systemConfig, "value: system\n")

	newFlagSet := func() (*FlagSet, *string) {
		flagSet := NewFlagSet()
		flagSet.Marshal = true
		value := new(string)
		flagSet.StringVar(value, "value", "compiled", "test value")
		flagSet.SetConfigFilePaths(systemConfig, userConfig)
		return flagSet, value
	}

	firstParse, firstValue := newFlagSet()
	require.NoError(t, firstParse.Parse(""), "create the primary config")
	require.Equal(t, "system", *firstValue)

	secondParse, secondValue := newFlagSet()
	require.NoError(t, secondParse.Parse(""), "reload the generated primary config")
	require.Equal(t, "system", *secondValue)
}

func TestParseDoesNotReloadNewPrimaryConfig(t *testing.T) {
	t.Setenv("GOFLAGS_TEST_AUTH", "env-token")

	configFile := filepath.Join(t.TempDir(), "config.yaml")
	flagSet := NewFlagSet()
	flagSet.Marshal = true
	var authValue string
	flagSet.AuthVar(&authValue, "auth", "GOFLAGS_TEST_AUTH", "authentication token")
	flagSet.SetConfigFilePath(configFile)

	require.NoError(t, flagSet.Parse(""))
	require.Equal(t, "env-token", authValue)
	require.FileExists(t, configFile)
}

func TestConfigFileCascadeIgnoresMissingLowerPriorityFile(t *testing.T) {
	tempDir := t.TempDir()
	missingConfig := filepath.Join(tempDir, "missing.yaml")
	userConfig := filepath.Join(tempDir, "user.yaml")
	writeTestConfig(t, userConfig, "value: user\n")

	flagSet := NewFlagSet()
	var value string
	flagSet.StringVar(&value, "value", "compiled", "test value")
	flagSet.SetConfigFilePaths(missingConfig, userConfig)

	require.NoError(t, flagSet.Parse(""))
	require.Equal(t, "user", value)
}

func TestConfigFileCascadeCreatesPrimaryWithMissingLowerPriorityFile(t *testing.T) {
	tempDir := t.TempDir()
	systemConfig := filepath.Join(tempDir, "missing.yaml")
	userConfig := filepath.Join(tempDir, "user", "config.yaml")

	flagSet := NewFlagSet()
	var value string
	flagSet.StringVar(&value, "value", "compiled", "test value")
	flagSet.SetConfigFilePaths(systemConfig, userConfig)

	require.NoError(t, flagSet.Parse(""))
	require.Equal(t, "compiled", value)
	require.FileExists(t, userConfig)
}

func TestConfigFileCascadeReturnsLowerPrioritySourceError(t *testing.T) {
	tempDir := t.TempDir()
	systemConfig := filepath.Join(tempDir, "system.yaml")
	userConfig := filepath.Join(tempDir, "user.yaml")
	writeTestConfig(t, systemConfig, "value: [\n")
	writeTestConfig(t, userConfig, "value: user\n")

	flagSet := NewFlagSet()
	var value string
	flagSet.StringVar(&value, "value", "compiled", "test value")
	flagSet.SetConfigFilePaths(systemConfig, userConfig)

	err := flagSet.Parse("")
	require.ErrorContains(t, err, fmt.Sprintf("%q", systemConfig))
}

func TestMergeConfigFileReturnsMissingFileError(t *testing.T) {
	flagSet := NewFlagSet()

	err := flagSet.MergeConfigFile(filepath.Join(t.TempDir(), "missing.yaml"))
	require.ErrorIs(t, err, os.ErrNotExist)
}

func TestMergeConfigFileLoadsDirectCommandLineFlag(t *testing.T) {
	configFile := filepath.Join(t.TempDir(), "config.yaml")
	writeTestConfig(t, configFile, "direct: configured\n")

	flagSet := NewFlagSet()
	var value string
	flagSet.CommandLine.StringVar(&value, "direct", "compiled", "direct flag")

	require.NoError(t, flagSet.MergeConfigFile(configFile))
	require.Equal(t, "configured", value)
}

func TestMergeConfigFilePreservesProgrammaticValue(t *testing.T) {
	tests := []struct {
		name   string
		mutate func(*testing.T, *FlagSet, *string)
	}{
		{
			name: "bound variable",
			mutate: func(_ *testing.T, _ *FlagSet, value *string) {
				*value = "programmatic"
			},
		},
		{
			name: "flag value",
			mutate: func(t *testing.T, flagSet *FlagSet, _ *string) {
				require.NoError(t, flagSet.CommandLine.Lookup("value").Value.Set("programmatic"))
			},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			configFile := filepath.Join(t.TempDir(), "config.yaml")
			writeTestConfig(t, configFile, "value: configured\n")

			flagSet := NewFlagSet()
			value := "compiled"
			flagSet.StringVar(&value, "value", value, "test value")
			test.mutate(t, flagSet, &value)

			require.NoError(t, flagSet.MergeConfigFile(configFile))
			require.Equal(t, "programmatic", value)
		})
	}
}

func TestMergeConfigFilePreservesProgrammaticDynamicValue(t *testing.T) {
	configFile := filepath.Join(t.TempDir(), "config.yaml")
	writeTestConfig(t, configFile, "value: configured\n")

	flagSet := NewFlagSet()
	value := "compiled"
	flagSet.DynamicVar(&value, "value", value, "test value")
	value = "programmatic"

	require.NoError(t, flagSet.MergeConfigFile(configFile))
	require.Equal(t, "programmatic", value)
}

func TestMergeConfigFileUsesDynamicRegistrationState(t *testing.T) {
	t.Run("untouched zero value", func(t *testing.T) {
		configFile := filepath.Join(t.TempDir(), "config.yaml")
		writeTestConfig(t, configFile, "value: 100\n")

		flagSet := NewFlagSet()
		var value int
		flagSet.DynamicVar(&value, "value", 50, "test value")

		require.NoError(t, flagSet.MergeConfigFile(configFile))
		require.Equal(t, 100, value)
	})

	t.Run("in-place slice mutation", func(t *testing.T) {
		configFile := filepath.Join(t.TempDir(), "config.yaml")
		writeTestConfig(t, configFile, "values:\n  - configured\n")

		flagSet := NewFlagSet()
		values := []string{"compiled"}
		flagSet.DynamicVar(&values, "values", values, "test values")
		values[0] = "programmatic"

		require.NoError(t, flagSet.MergeConfigFile(configFile))
		require.Equal(t, []string{"programmatic"}, values)
	})
}

func TestMapFlagValueStringsAreDeterministic(t *testing.T) {
	runtimeMap := RuntimeMap{kv: map[string]interface{}{"b": "2", "a": "1"}}
	rateLimitMap := RateLimitMap{kv: map[string]RateLimit{
		"b": {MaxCount: 2, Duration: time.Second},
		"a": {MaxCount: 1, Duration: time.Second},
	}}
	ports := Port{kv: map[int]struct{}{443: {}, 80: {}}}

	require.Equal(t, `{"a"="1"="b"="2"}`, runtimeMap.String())
	require.Equal(t, `{"a":"1/1s","b":"2/1s"}`, rateLimitMap.String())
	require.Equal(t, `(80,443)`, ports.String())
}

func TestMergeConfigFileMapUsesSourcePrecedence(t *testing.T) {
	tempDir := t.TempDir()
	lowerConfig := filepath.Join(tempDir, "lower.yaml")
	emptyConfig := filepath.Join(tempDir, "empty.yaml")
	higherConfig := filepath.Join(tempDir, "higher.yaml")
	writeTestConfig(t, lowerConfig, "values:\n  - a=1\n  - b=2\n")
	writeTestConfig(t, emptyConfig, "values: []\n")
	writeTestConfig(t, higherConfig, "values:\n  - final=3\n")

	flagSet := NewFlagSet()
	var values RuntimeMap
	flagSet.RuntimeMapVar(&values, "values", []string{"compiled=1"}, "test values")

	require.NoError(t, flagSet.MergeConfigFile(lowerConfig))
	require.NoError(t, flagSet.MergeConfigFile(emptyConfig))
	require.Empty(t, values.AsMap())
	require.NoError(t, flagSet.MergeConfigFile(higherConfig))
	require.Equal(t, map[string]interface{}{"final": "3"}, values.AsMap())
}

func TestMergeConfigFilePreservesCollectionOnError(t *testing.T) {
	t.Run("invalid item type", func(t *testing.T) {
		configFile := filepath.Join(t.TempDir(), "config.yaml")
		writeTestConfig(t, configFile, "items:\n  - valid\n  - 1\n")

		flagSet := NewFlagSet()
		var items StringSlice
		flagSet.StringSliceVar(&items, "items", []string{"existing"}, "test items", StringSliceOptions)

		require.Error(t, flagSet.MergeConfigFile(configFile))
		require.Equal(t, StringSlice{"existing"}, items)
	})

	t.Run("set error", func(t *testing.T) {
		configFile := filepath.Join(t.TempDir(), "config.yaml")
		writeTestConfig(t, configFile, "rate-limits:\n  - valid=2/s\n  - invalid=bad\n")

		flagSet := NewFlagSet()
		var rateLimits RateLimitMap
		flagSet.RateLimitMapVar(&rateLimits, "rate-limits", []string{"existing=1/s"}, "test rate limits", StringSliceOptions)

		require.Error(t, flagSet.MergeConfigFile(configFile))
		require.Equal(t, map[string]RateLimit{
			"existing": {MaxCount: 1, Duration: time.Second},
		}, rateLimits.AsMap())
	})
}

func TestMergeConfigFilePreservesDurationOnError(t *testing.T) {
	configFile := filepath.Join(t.TempDir(), "config.yaml")
	writeTestConfig(t, configFile, "duration: invalid\n")

	flagSet := NewFlagSet()
	duration := time.Hour
	flagSet.DurationVar(&duration, "duration", duration, "test duration")

	require.Error(t, flagSet.MergeConfigFile(configFile))
	require.Equal(t, time.Hour, duration)
}

func TestMergeConfigFilePreservesScalarOnListError(t *testing.T) {
	configFile := filepath.Join(t.TempDir(), "config.yaml")
	writeTestConfig(t, configFile, "count:\n  - \"1\"\n  - invalid\n")

	flagSet := NewFlagSet()
	count := 7
	flagSet.IntVar(&count, "count", count, "test count")

	require.Error(t, flagSet.MergeConfigFile(configFile))
	require.Equal(t, 7, count)
}

func TestConfigFileRejectsEmptyListForNonCollection(t *testing.T) {
	t.Run("cascade", func(t *testing.T) {
		tempDir := t.TempDir()
		lowerConfig := filepath.Join(tempDir, "lower.yaml")
		higherConfig := filepath.Join(tempDir, "higher.yaml")
		writeTestConfig(t, lowerConfig, "value: lower\n")
		writeTestConfig(t, higherConfig, "value: []\n")

		flagSet := NewFlagSet()
		value := "compiled"
		flagSet.StringVar(&value, "value", value, "test value")
		flagSet.SetConfigFilePaths(lowerConfig, higherConfig)

		require.ErrorContains(t, flagSet.Parse(""), "empty list")
		require.Equal(t, "compiled", value)
	})

	t.Run("sequential merge", func(t *testing.T) {
		tempDir := t.TempDir()
		lowerConfig := filepath.Join(tempDir, "lower.yaml")
		higherConfig := filepath.Join(tempDir, "higher.yaml")
		writeTestConfig(t, lowerConfig, "value: lower\n")
		writeTestConfig(t, higherConfig, "value: []\n")

		flagSet := NewFlagSet()
		value := "compiled"
		flagSet.StringVar(&value, "value", value, "test value")

		require.NoError(t, flagSet.MergeConfigFile(lowerConfig))
		require.ErrorContains(t, flagSet.MergeConfigFile(higherConfig), "empty list")
		require.Equal(t, "lower", value)
	})

	t.Run("custom flag value", func(t *testing.T) {
		configFile := filepath.Join(t.TempDir(), "config.yaml")
		writeTestConfig(t, configFile, "value: []\n")

		flagSet := NewFlagSet()
		value := scalarConfigValue("compiled")
		flagSet.Var(&value, "value", "test value")

		require.ErrorContains(t, flagSet.MergeConfigFile(configFile), "empty list")
		require.Equal(t, scalarConfigValue("compiled"), value)
	})
}

type scalarConfigValue string

func (value *scalarConfigValue) Set(input string) error {
	*value = scalarConfigValue(input)
	return nil
}

func (value *scalarConfigValue) String() string {
	return string(*value)
}

func TestMergeConfigFileRollsBackLayerOnValueError(t *testing.T) {
	tempDir := t.TempDir()
	invalidConfig := filepath.Join(tempDir, "invalid.yaml")
	validConfig := filepath.Join(tempDir, "valid.yaml")
	writeTestConfig(t, invalidConfig, "first: configured\nsecond: invalid\n")
	writeTestConfig(t, validConfig, "first: final\nsecond: 8\n")

	flagSet := NewFlagSet()
	first := "compiled"
	second := 7
	flagSet.StringVar(&first, "first", first, "first value")
	flagSet.IntVar(&second, "second", second, "second value")

	require.Error(t, flagSet.MergeConfigFile(invalidConfig))
	require.Equal(t, "compiled", first)
	require.Equal(t, 7, second)

	require.NoError(t, flagSet.MergeConfigFile(validConfig))
	require.Equal(t, "final", first)
	require.Equal(t, 8, second)
}

func TestConfigFileCascadeDirectAliasesUseSourcePrecedence(t *testing.T) {
	tempDir := t.TempDir()
	lowerConfig := filepath.Join(tempDir, "lower.yaml")
	higherConfig := filepath.Join(tempDir, "higher.yaml")
	writeTestConfig(t, lowerConfig, "z-alias: lower\n")
	writeTestConfig(t, higherConfig, "a-alias: higher\n")

	flagSet := NewFlagSet()
	var value string
	flagSet.CommandLine.StringVar(&value, "z-alias", "compiled", "lower alias")
	flagSet.CommandLine.StringVar(&value, "a-alias", "compiled", "higher alias")
	flagSet.SetConfigFilePaths(lowerConfig, higherConfig)

	require.NoError(t, flagSet.Parse(""))
	require.Equal(t, "higher", value)
}

func TestConfigFileCLIValuePrecedenceAcrossRegistrations(t *testing.T) {
	tests := []struct {
		name     string
		register func(*FlagSet, *string)
	}{
		{
			name: "direct command-line flags",
			register: func(flagSet *FlagSet, value *string) {
				flagSet.CommandLine.StringVar(value, "primary", "compiled", "primary flag")
				flagSet.CommandLine.StringVar(value, "alias", "compiled", "alias flag")
			},
		},
		{
			name: "goflags registrations",
			register: func(flagSet *FlagSet, value *string) {
				flagSet.StringVar(value, "primary", "compiled", "primary flag")
				flagSet.StringVar(value, "alias", "compiled", "alias flag")
			},
		},
		{
			name: "dynamic registrations",
			register: func(flagSet *FlagSet, value *string) {
				flagSet.DynamicVar(value, "primary", "compiled", "primary flag")
				flagSet.DynamicVar(value, "alias", "compiled", "alias flag")
			},
		},
		{
			name: "enum registrations",
			register: func(flagSet *FlagSet, value *string) {
				allowedTypes := AllowdTypes{"compiled": 0, "configured": 1, "cli": 2}
				flagSet.EnumVar(value, "primary", 0, "primary flag", allowedTypes)
				flagSet.EnumVar(value, "alias", 0, "alias flag", allowedTypes)
			},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			configFile := filepath.Join(t.TempDir(), "config.yaml")
			writeTestConfig(t, configFile, "alias: configured\n")

			flagSet := NewFlagSet()
			var value string
			test.register(flagSet, &value)
			flagSet.SetConfigFilePath(configFile)

			require.NoError(t, flagSet.Parse("-primary=cli"))
			require.Equal(t, "cli", value)
		})
	}
}

func TestConfigFileCascadeUsesWinningAliasParser(t *testing.T) {
	tempDir := t.TempDir()
	lowerConfig := filepath.Join(tempDir, "lower.yaml")
	higherConfig := filepath.Join(tempDir, "higher.yaml")
	writeTestConfig(t, lowerConfig, "lower:\n  - lower\n")
	writeTestConfig(t, higherConfig, "higher:\n  - higher\n")

	flagSet := NewFlagSet()
	var values []string
	flagSet.EnumSliceVar(&values, "lower", []EnumVariable{0}, "lower values", AllowdTypes{"compiled": 0, "lower": 1})
	flagSet.EnumSliceVar(&values, "higher", []EnumVariable{0}, "higher values", AllowdTypes{"compiled": 0, "higher": 1})
	flagSet.SetConfigFilePaths(lowerConfig, higherConfig)

	require.NoError(t, flagSet.Parse(""))
	require.Equal(t, []string{"higher"}, values)
}

func TestMergeConfigFilePreservesLongAliasPrecedence(t *testing.T) {
	configFile := filepath.Join(t.TempDir(), "config.yaml")
	writeTestConfig(t, configFile, "a: short\naliased: long\n")

	flagSet := NewFlagSet()
	var value string
	flagSet.StringVarP(&value, "aliased", "a", "compiled", "aliased flag")

	require.NoError(t, flagSet.MergeConfigFile(configFile))
	require.Equal(t, "long", value)
}

func TestMergeConfigFileUsesSourcePrecedence(t *testing.T) {
	tempDir := t.TempDir()
	defaultConfig := filepath.Join(tempDir, "default.yaml")
	systemConfig := filepath.Join(tempDir, "system.yaml")
	userConfig := filepath.Join(tempDir, "user.yaml")
	writeTestConfig(t, defaultConfig, "")
	writeTestConfig(t, systemConfig, "value: system\nitems:\n  - system\ncli-value: system\n")
	writeTestConfig(t, userConfig, "value: user\nitems:\n  - user\ncli-value: user\n")

	flagSet := NewFlagSet()
	var value, cliValue string
	var items StringSlice
	flagSet.StringVar(&value, "value", "compiled", "test value")
	flagSet.StringSliceVar(&items, "items", []string{"compiled"}, "test items", StringSliceOptions)
	flagSet.StringVar(&cliValue, "cli-value", "compiled", "CLI value")
	flagSet.SetConfigFilePath(defaultConfig)

	require.NoError(t, flagSet.Parse("-cli-value", "compiled"))
	require.NoError(t, flagSet.MergeConfigFile(systemConfig))
	require.NoError(t, flagSet.MergeConfigFile(userConfig))
	require.Equal(t, "user", value)
	require.Equal(t, StringSlice{"user"}, items)
	require.Equal(t, "compiled", cliValue)
}

func TestConfigFileCascadeReplacesBuiltInCollections(t *testing.T) {
	tempDir := t.TempDir()
	systemConfig := filepath.Join(tempDir, "system.yaml")
	userConfig := filepath.Join(tempDir, "user.yaml")
	writeTestConfig(t, systemConfig, `
ports:
  - "81"
rate-limits:
  - system=2/s
severities:
  - low
dynamic:
  - system
`)
	writeTestConfig(t, userConfig, `
ports:
  - "82"
rate-limits:
  - user=3/s
severities:
  - medium
  - high
dynamic:
  - user
`)

	flagSet := NewFlagSet()
	var ports Port
	var rateLimits RateLimitMap
	var severities []string
	dynamic := []string{"compiled"}
	flagSet.PortVar(&ports, "ports", []string{"80"}, "test ports")
	flagSet.RateLimitMapVar(&rateLimits, "rate-limits", []string{"compiled=1/s"}, "test rate limits", StringSliceOptions)
	flagSet.EnumSliceVar(&severities, "severities", []EnumVariable{0}, "test severities", AllowdTypes{
		"low":    0,
		"medium": 1,
		"high":   2,
	})
	flagSet.DynamicVar(&dynamic, "dynamic", []string{"compiled"}, "test dynamic values")
	flagSet.SetConfigFilePaths(systemConfig, userConfig)

	require.NoError(t, flagSet.Parse(""))
	require.Equal(t, []int{82}, ports.AsPorts())
	require.Equal(t, map[string]RateLimit{
		"user": {MaxCount: 3, Duration: time.Second},
	}, rateLimits.AsMap())
	require.Equal(t, []string{"medium", "high"}, severities)
	require.Equal(t, []string{"user"}, dynamic)
}

func TestConfigFileCascadeReturnsValueError(t *testing.T) {
	tempDir := t.TempDir()
	lowerConfig := filepath.Join(tempDir, "lower.yaml")
	higherConfig := filepath.Join(tempDir, "higher.yaml")
	writeTestConfig(t, lowerConfig, "count: 2\n")
	writeTestConfig(t, higherConfig, "count: not-an-integer\n")

	flagSet := NewFlagSet()
	var count int
	flagSet.IntVar(&count, "count", 1, "test count")
	flagSet.SetConfigFilePaths(lowerConfig, higherConfig)

	err := flagSet.Parse("")
	require.ErrorContains(t, err, `set config option "count"`)
	require.ErrorContains(t, err, fmt.Sprintf("%q", higherConfig))
	require.NotContains(t, err.Error(), fmt.Sprintf("%q", lowerConfig))
}

func BenchmarkMergeConfigAssignments(b *testing.B) {
	for _, size := range []int{100, 500, 1000} {
		flagSet := NewFlagSet()
		values := make([]string, size)
		targets := make([]configTarget, size)
		for i := range size {
			name := fmt.Sprintf("flag-%d", i)
			flagSet.CommandLine.StringVar(&values[i], name, "", "benchmark flag")
			targets[i] = newConfigTarget(nil, name, flagSet.CommandLine.Lookup(name).Value)
		}

		b.Run(fmt.Sprintf("flags=%d", size), func(b *testing.B) {
			for b.Loop() {
				assignments := newConfigAssignments(size)
				for _, target := range targets {
					assignments.merge(configAssignment{target: target})
				}
				if len(assignments.ordered) != size {
					b.Fatalf("got %d assignments, want %d", len(assignments.ordered), size)
				}
			}
		})
	}
}

func writeTestConfig(t *testing.T, filePath, data string) {
	t.Helper()
	require.NoError(t, os.WriteFile(filePath, []byte(data), permissionutil.ConfigFilePermission))
}

func TestConfigOnlyDataTypes(t *testing.T) {
	flagSet := NewFlagSet()
	var data StringSlice

	flagSet.StringSliceVarConfigOnly(&data, "config-only", []string{}, "String slice config only flag example")

	require.Nil(t, flagSet.CommandLine.Lookup("config-only"), "config-only flag should not be registered")

	configFileData := `
config-only:
 - test
 - test2
 `
	configFile := filepath.Join(t.TempDir(), "config.yaml")
	writeTestConfig(t, configFile, configFileData)

	err := flagSet.MergeConfigFile(configFile)
	require.Nil(t, err, "could not merge temporary config")

	require.Equal(t, StringSlice{"test", "test2"}, data, "could not get correct string slice")
	tearDown(t.Name())
}
