package goflags

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path"
	"reflect"
	"slices"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// MergeConfigFile reads one higher-priority config layer.
// Explicit command-line flags keep precedence over the file. Active common
// flag handlers are refreshed after a successful merge.
func (flagSet *FlagSet) MergeConfigFile(file string) error {
	if err := flagSet.mergeConfigFiles([]string{file}); err != nil {
		return err
	}

	flagSet.refreshCommonFlagsHandlers()

	return nil
}

// generateDefaultConfig generates a default YAML config file for a flagset.
// When marshal is false, the generated options remain commented examples.
func (flagSet *FlagSet) generateDefaultConfig(marshal bool) []byte {
	hashes := make(map[string]struct{})
	configBuffer := &bytes.Buffer{}
	configBuffer.WriteString("# ")
	configBuffer.WriteString(path.Base(os.Args[0]))
	configBuffer.WriteString(" config file\n# generated by https://github.com/projectdiscovery/goflags\n\n")

	// Marshal natively when requested. On error, fall back to commented examples.
	if marshal {
		flagsToMarshall := make(map[string]interface{})

		flagSet.flagKeys.forEach(func(key string, data *FlagData) {
			canonicalKey := data.long
			if canonicalKey == "" {
				canonicalKey = data.short
			}

			if key == canonicalKey && !data.skipMarshal && !data.skipConfig {
				flagsToMarshall[canonicalKey] = data.defaultValue
			}
		})

		flagSetBytes, err := yaml.Marshal(flagsToMarshall)
		if err == nil {
			configBuffer.Write(flagSetBytes)
			return configBuffer.Bytes()
		}
	}

	flagSet.flagKeys.forEach(func(key string, data *FlagData) {
		if data.skipConfig {
			return
		}

		dataHash := data.Hash()
		if _, ok := hashes[dataHash]; ok {
			return
		}
		hashes[dataHash] = struct{}{}

		configBuffer.WriteString("# ")
		configBuffer.WriteString(strings.ToLower(data.usage))
		configBuffer.WriteString("\n")
		configBuffer.WriteString("#")
		configBuffer.WriteString(data.long)
		configBuffer.WriteString(": ")
		switch defaultValue := data.defaultValue.(type) {
		case string:
			configBuffer.WriteString(defaultValue)
		case flag.Value:
			configBuffer.WriteString(defaultValue.String())
		case StringSlice:
			configBuffer.WriteString(defaultValue.String())
		}

		configBuffer.WriteString("\n\n")
	})

	return bytes.TrimSuffix(configBuffer.Bytes(), []byte("\n\n"))
}

func existingConfigFilePaths(filePaths []string) ([]string, error) {
	existingPaths := make([]string, 0, len(filePaths))
	for _, filePath := range filePaths {
		if _, err := os.Stat(filePath); errors.Is(err, os.ErrNotExist) {
			continue
		} else if err != nil {
			return nil, fmt.Errorf("inspect config file %q: %w", filePath, err)
		}

		existingPaths = append(existingPaths, filePath)
	}

	return existingPaths, nil
}

func readConfigFile(filePath string) (map[string]interface{}, error) {
	file, err := os.Open(filePath)
	if err != nil {
		return nil, err
	}
	defer func() {
		_ = file.Close()
	}()

	data := make(map[string]interface{})
	err = yaml.NewDecoder(file).Decode(&data)
	if errors.Is(err, io.EOF) {
		return data, nil
	}
	if err != nil {
		return nil, err
	}

	return data, nil
}

type configTargetKey struct {
	value    interface{}
	flagData *FlagData
	name     string
}

type configTarget struct {
	key       configTargetKey
	name      string
	flagValue flag.Value
}

func newConfigTarget(flagData *FlagData, name string, flagValue flag.Value) configTarget {
	target := configTarget{
		name:      name,
		flagValue: flagValue,
	}

	value := flagValueTarget(flagValue)
	if value.IsValid() && value.Kind() == reflect.Pointer && !value.IsNil() {
		target.key.value = value.Interface()
	} else if flagData != nil {
		target.key.flagData = flagData
	} else {
		target.key.name = name
	}

	return target
}

type configAssignment struct {
	target     configTarget
	value      interface{}
	sourcePath string
}

type configValueState struct {
	target configTarget
	value  interface{}
}

type configAssignments struct {
	ordered []configAssignment
	indexes map[configTargetKey]int
}

func newConfigAssignments(capacity int) configAssignments {
	return configAssignments{
		ordered: make([]configAssignment, 0, capacity),
		indexes: make(map[configTargetKey]int, capacity),
	}
}

func (assignments *configAssignments) merge(assignment configAssignment) {
	if index, ok := assignments.indexes[assignment.target.key]; ok {
		assignments.ordered[index] = assignment
		return
	}

	assignments.indexes[assignment.target.key] = len(assignments.ordered)
	assignments.ordered = append(assignments.ordered, assignment)
}

func (flagSet *FlagSet) mergeConfigFiles(filePaths []string) error {
	assignments := newConfigAssignments(len(flagSet.flagKeys.keys))

	for _, filePath := range filePaths {
		data, err := readConfigFile(filePath)
		if err != nil {
			return fmt.Errorf("read config file %q: %w", filePath, err)
		}

		for _, key := range flagSet.flagKeys.keys {
			flagData := flagSet.flagKeys.values[key]
			value, ok := data[key]
			if !ok || flagData.skipConfig {
				continue
			}

			flagValue := flagData.field
			if registeredFlag := flagSet.CommandLine.Lookup(key); registeredFlag != nil {
				flagValue = registeredFlag.Value
			}
			if flagValue == nil {
				return fmt.Errorf("config option %q has no registered value", flagData.long)
			}

			name := flagData.long
			if name == "" {
				name = key
			}

			assignments.merge(configAssignment{
				target:     newConfigTarget(flagData, name, flagValue),
				value:      value,
				sourcePath: filePath,
			})
		}

		flagSet.CommandLine.VisitAll(func(registeredFlag *flag.Flag) {
			if _, ok := flagSet.flagKeys.values[registeredFlag.Name]; ok {
				return
			}

			if value, ok := data[registeredFlag.Name]; ok {
				assignments.merge(configAssignment{
					target:     newConfigTarget(nil, registeredFlag.Name, registeredFlag.Value),
					value:      value,
					sourcePath: filePath,
				})
			}
		})
	}

	return flagSet.applyConfigValues(assignments.ordered)
}

func flagValueTarget(value flag.Value) reflect.Value {
	switch value := value.(type) {
	case *dynamicFlag:
		return reflect.ValueOf(value.field)
	case *AuthVar:
		return reflect.ValueOf(value.field)
	case *EnumSliceVar:
		return reflect.ValueOf(value.value)
	case *EnumVar:
		return reflect.ValueOf(value.value)
	default:
		return reflect.ValueOf(value)
	}
}

type appliedConfigChange struct {
	targetKey configTargetKey
	restore   func()
	oldState  configValueState
	hadState  bool
}

func (flagSet *FlagSet) applyConfigValues(assignments []configAssignment) error {
	cliTargets := make(map[configTargetKey]struct{})
	flagSet.CommandLine.Visit(func(registeredFlag *flag.Flag) {
		target := newConfigTarget(flagSet.flagKeys.values[registeredFlag.Name], registeredFlag.Name, registeredFlag.Value)
		cliTargets[target.key] = struct{}{}
	})

	changes := make([]appliedConfigChange, 0, len(assignments))
	for _, assignment := range assignments {
		if _, cliSet := cliTargets[assignment.target.key]; cliSet {
			continue
		}

		if flagSet.configValueIsCallerOwned(assignment.target) {
			continue
		}

		oldState, hadState := flagSet.appliedConfigValues[assignment.target.key]
		restore, err := setConfigValue(assignment.target.flagValue, assignment.value)
		if err != nil {
			flagSet.rollbackConfigChanges(changes)
			return fmt.Errorf("set config option %q from %q: %w", assignment.target.name, assignment.sourcePath, err)
		}

		flagSet.recordAppliedConfigValue(assignment.target)
		changes = append(changes, appliedConfigChange{
			targetKey: assignment.target.key,
			restore:   restore,
			oldState:  oldState,
			hadState:  hadState,
		})
	}

	return nil
}

func (flagSet *FlagSet) rollbackConfigChanges(changes []appliedConfigChange) {
	for i := len(changes) - 1; i >= 0; i-- {
		change := changes[i]
		change.restore()
		if change.hadState {
			flagSet.appliedConfigValues[change.targetKey] = change.oldState
		} else {
			delete(flagSet.appliedConfigValues, change.targetKey)
		}
	}
}

func (flagSet *FlagSet) configValueIsCallerOwned(target configTarget) bool {
	if appliedValue, ok := flagSet.appliedConfigValues[target.key]; ok {
		return !configValueMatchesSnapshot(appliedValue.target.flagValue, appliedValue.value)
	}

	if dynamicValue, ok := target.flagValue.(*dynamicFlag); ok {
		return !configValueMatchesSnapshot(target.flagValue, dynamicValue.initialValue)
	}

	registeredFlag := flagSet.CommandLine.Lookup(target.name)
	return registeredFlag != nil && !strings.EqualFold(registeredFlag.DefValue, target.flagValue.String())
}

func (flagSet *FlagSet) recordAppliedConfigValue(target configTarget) {
	if flagSet.appliedConfigValues == nil {
		flagSet.appliedConfigValues = make(map[configTargetKey]configValueState)
	}

	flagSet.appliedConfigValues[target.key] = configValueState{
		target: target,
		value:  configValueSnapshot(target.flagValue),
	}
}

func configValueSnapshot(flagValue flag.Value) interface{} {
	switch value := flagValue.(type) {
	case *StringSlice:
		return slices.Clone(*value)
	case *RuntimeMap:
		if value.kv == nil {
			return map[string]interface{}(nil)
		}
		snapshot := make(map[string]interface{}, len(value.kv))
		for key, item := range value.kv {
			snapshot[key] = item
		}
		return snapshot
	case *RateLimitMap:
		if value.kv == nil {
			return map[string]RateLimit(nil)
		}
		snapshot := make(map[string]RateLimit, len(value.kv))
		for key, item := range value.kv {
			snapshot[key] = item
		}
		return snapshot
	case *Port:
		if value.kv == nil {
			return map[int]struct{}(nil)
		}
		snapshot := make(map[int]struct{}, len(value.kv))
		for key := range value.kv {
			snapshot[key] = struct{}{}
		}
		return snapshot
	case *EnumSliceVar:
		return slices.Clone(*value.value)
	case *EnumVar:
		return *value.value
	case *durationValue:
		return time.Duration(*value)
	case *AuthVar:
		return *value.field
	case *dynamicFlag:
		return dynamicFieldSnapshot(value.field)
	}

	value := reflect.ValueOf(flagValue)
	if value.IsValid() && value.Kind() == reflect.Pointer && !value.IsNil() {
		field := value.Elem()
		switch field.Kind() {
		case reflect.Bool, reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
			reflect.Float32, reflect.Float64, reflect.String:
			return field.Interface()
		}
	}

	return flagValue.String()
}

func configValueMatchesSnapshot(flagValue flag.Value, snapshot interface{}) bool {
	switch value := flagValue.(type) {
	case *StringSlice:
		previous, ok := snapshot.(StringSlice)
		return ok && slices.Equal(*value, previous)
	case *RuntimeMap:
		previous, ok := snapshot.(map[string]interface{})
		if !ok || len(value.kv) != len(previous) {
			return false
		}
		for key, item := range value.kv {
			previousItem, exists := previous[key]
			if !exists || !reflect.DeepEqual(previousItem, item) {
				return false
			}
		}
		return true
	case *RateLimitMap:
		previous, ok := snapshot.(map[string]RateLimit)
		if !ok || len(value.kv) != len(previous) {
			return false
		}
		for key, item := range value.kv {
			previousItem, exists := previous[key]
			if !exists || previousItem != item {
				return false
			}
		}
		return true
	case *Port:
		previous, ok := snapshot.(map[int]struct{})
		if !ok || len(value.kv) != len(previous) {
			return false
		}
		for key := range value.kv {
			if _, ok := previous[key]; !ok {
				return false
			}
		}
		return true
	case *EnumSliceVar:
		previous, ok := snapshot.([]string)
		return ok && slices.Equal(*value.value, previous)
	case *EnumVar:
		previous, ok := snapshot.(string)
		return ok && *value.value == previous
	case *durationValue:
		previous, ok := snapshot.(time.Duration)
		return ok && time.Duration(*value) == previous
	case *AuthVar:
		previous, ok := snapshot.(string)
		return ok && *value.field == previous
	case *dynamicFlag:
		return reflect.DeepEqual(reflect.ValueOf(value.field).Elem().Interface(), snapshot)
	default:
		return reflect.DeepEqual(configValueSnapshot(flagValue), snapshot)
	}
}

func setConfigValue(flagValue flag.Value, value interface{}) (func(), error) {
	var set func() error
	switch value := value.(type) {
	case nil:
		return nil, errors.New("null values are not supported")
	case string:
		set = func() error { return flagValue.Set(value) }
	case bool:
		set = func() error { return flagValue.Set(strconv.FormatBool(value)) }
	case int:
		set = func() error { return flagValue.Set(strconv.Itoa(value)) }
	case int64:
		set = func() error { return flagValue.Set(strconv.FormatInt(value, 10)) }
	case uint64:
		set = func() error { return flagValue.Set(strconv.FormatUint(value, 10)) }
	case float64:
		set = func() error { return flagValue.Set(strconv.FormatFloat(value, 'g', -1, 64)) }
	case time.Duration:
		set = func() error { return flagValue.Set(value.String()) }
	case []interface{}:
		values := make([]string, len(value))
		for i, item := range value {
			itemValue, ok := item.(string)
			if !ok {
				return nil, fmt.Errorf("list item %d has type %T, expected string", i, item)
			}
			values[i] = itemValue
		}
		if len(values) == 0 && !configValueAcceptsEmptyList(flagValue) {
			return nil, errors.New("empty list is not supported for a non-collection option")
		}
		set = func() error { return setConfigListValue(flagValue, values) }
	default:
		return nil, fmt.Errorf("unsupported value type %T", value)
	}

	restore := resetConfigValue(flagValue)
	if err := set(); err != nil {
		restore()
		return nil, err
	}

	return restore, nil
}

func configValueAcceptsEmptyList(flagValue flag.Value) bool {
	switch value := flagValue.(type) {
	case *StringSlice, *RuntimeMap, *RateLimitMap, *Port, *EnumSliceVar:
		return true
	case *dynamicFlag:
		return reflect.TypeOf(value.field).Elem().Kind() == reflect.Slice
	default:
		return false
	}
}

func setConfigListValue(flagValue flag.Value, values []string) error {
	if enumSlice, ok := flagValue.(*EnumSliceVar); ok {
		if len(values) == 0 {
			return nil
		}

		return enumSlice.Set(strings.Join(values, ","))
	}

	for _, item := range values {
		if err := flagValue.Set(item); err != nil {
			return err
		}
	}

	return nil
}

func resetConfigValue(flagValue flag.Value) func() {
	switch value := flagValue.(type) {
	case *StringSlice:
		oldValue := *value
		*value = nil
		return func() { *value = oldValue }
	case *RuntimeMap:
		oldValue := value.kv
		value.kv = nil
		return func() { value.kv = oldValue }
	case *RateLimitMap:
		oldValue := value.kv
		value.kv = nil
		return func() { value.kv = oldValue }
	case *Port:
		oldValue := value.kv
		value.kv = nil
		return func() { value.kv = oldValue }
	case *EnumSliceVar:
		oldValue := *value.value
		*value.value = nil
		return func() { *value.value = oldValue }
	case *EnumVar:
		oldValue := *value.value
		return func() { *value.value = oldValue }
	case *durationValue:
		oldValue := *value
		return func() { *value = oldValue }
	case *AuthVar:
		oldValue := *value.field
		oldEnvValue, oldEnvSet := os.LookupEnv(value.envKey)
		return func() {
			*value.field = oldValue
			if value.envKey == "" {
				return
			}

			if oldEnvSet {
				_ = os.Setenv(value.envKey, oldEnvValue)
			} else {
				_ = os.Unsetenv(value.envKey)
			}
		}
	case *dynamicFlag:
		field := reflect.ValueOf(value.field).Elem()
		oldValue := reflect.New(field.Type()).Elem()
		oldValue.Set(field)
		if field.Kind() == reflect.Slice {
			field.Set(reflect.Zero(field.Type()))
		}
		return func() { field.Set(oldValue) }
	}

	value := reflect.ValueOf(flagValue)
	if value.IsValid() && value.Kind() == reflect.Pointer && !value.IsNil() {
		field := value.Elem()
		switch field.Kind() {
		case reflect.Bool, reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
			reflect.Float32, reflect.Float64, reflect.String:
			oldValue := reflect.New(field.Type()).Elem()
			oldValue.Set(field)

			return func() { field.Set(oldValue) }
		}
	}

	return func() {}
}
