package goflags

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestGenerateDefaultConfig(t *testing.T) {
	f := New()

	example := `# goflags.test default config file
# generated by https://github.com/projectdiscovery/goflags

# default value for a test flag example
#test: test-default-value

# string slice flag example value
#slice: ["item1", "item2"]`

	var data string
	var data2 StringSlice
	f.StringVar(&data, "test", "test-default-value", "Default value for a test flag example")
	f.StringSliceVar(&data2, "slice", []string{"item1", "item2"}, "String slice flag example value")
	require.Equal(t, example, string(f.generateDefaultConfig()), "could not get correct default config")
}
