name: Manual Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - "debug-issue-103"


jobs:  
  build:
    name: Manual Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test
        run: go test ./...

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Build
        run: go build .